# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bmi-finder.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BMI(object):
    def setupUi(self, BMI):
        BMI.setObjectName("BMI")
        BMI.resize(320, 457)
        BMI.setMinimumSize(QtCore.QSize(320, 457))
        BMI.setMaximumSize(QtCore.QSize(320, 457))
        BMI.setSizeIncrement(QtCore.QSize(320, 501))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Ubuntu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BMI.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(BMI)
        self.centralwidget.setObjectName("centralwidget")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(120, 10, 51, 21))
        self.label_8.setStyleSheet("font: 20pt \"DejaVu Sans\";\n"
"font: italic 20pt \"Sans Uralic\";\n"
"")
        self.label_8.setObjectName("label_8")
        self.Burden = QtWidgets.QLabel(self.centralwidget)
        self.Burden.setGeometry(QtCore.QRect(20, 80, 51, 17))
        self.Burden.setObjectName("Burden")
        self.length = QtWidgets.QLabel(self.centralwidget)
        self.length.setGeometry(QtCore.QRect(20, 120, 51, 17))
        self.length.setObjectName("length")
        self.LB = QtWidgets.QLineEdit(self.centralwidget)
        self.LB.setGeometry(QtCore.QRect(200, 70, 113, 29))
        self.LB.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.LB.setObjectName("LB")
        self.LL = QtWidgets.QLineEdit(self.centralwidget)
        self.LL.setGeometry(QtCore.QRect(200, 110, 113, 29))
        self.LL.setObjectName("LL")
        self.CLOSE = QtWidgets.QPushButton(self.centralwidget)
        self.CLOSE.setGeometry(QtCore.QRect(120, 420, 92, 29))
        self.CLOSE.setObjectName("CLOSE")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(80, 380, 20, 20))
        self.label_7.setObjectName("label_7")
        self.Bmi = QtWidgets.QLabel(self.centralwidget)
        self.Bmi.setGeometry(QtCore.QRect(20, 340, 64, 17))
        self.Bmi.setObjectName("Bmi")
        self.Ubuntu = QtWidgets.QGraphicsView(self.centralwidget)
        self.Ubuntu.setGeometry(QtCore.QRect(10, 420, 31, 31))
        self.Ubuntu.setStyleSheet("background-image: url(:/Ubuntu.png);\n"
"border-image: url(:/Ubuntu.png);")
        self.Ubuntu.setObjectName("Ubuntu")
        self.SBM = QtWidgets.QLabel(self.centralwidget)
        self.SBM.setGeometry(QtCore.QRect(110, 340, 161, 17))
        self.SBM.setObjectName("SBM")
        self.SS = QtWidgets.QLabel(self.centralwidget)
        self.SS.setGeometry(QtCore.QRect(110, 380, 171, 17))
        self.SS.setObjectName("SS")
        self.Status = QtWidgets.QLabel(self.centralwidget)
        self.Status.setGeometry(QtCore.QRect(20, 380, 41, 16))
        self.Status.setObjectName("Status")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(80, 340, 16, 17))
        self.label_6.setObjectName("label_6")
        self.Run = QtWidgets.QPushButton(self.centralwidget)
        self.Run.setGeometry(QtCore.QRect(220, 420, 92, 29))
        self.Run.setObjectName("Run")
        self.gender = QtWidgets.QComboBox(self.centralwidget)
        self.gender.setGeometry(QtCore.QRect(20, 220, 91, 35))
        self.gender.setObjectName("gender")
        self.gender.addItem("")
        self.gender.addItem("")
        self.gender.addItem("")
        self.gender.addItem("")
        self.age = QtWidgets.QLabel(self.centralwidget)
        self.age.setGeometry(QtCore.QRect(20, 160, 51, 17))
        self.age.setObjectName("age")
        self.LA = QtWidgets.QLineEdit(self.centralwidget)
        self.LA.setGeometry(QtCore.QRect(200, 150, 113, 29))
        self.LA.setObjectName("LA")
        BMI.setCentralWidget(self.centralwidget)

        self.retranslateUi(BMI)
        self.CLOSE.clicked.connect(self.CLOSEs)
        self.Run.clicked.connect(self.RUN)
        QtCore.QMetaObject.connectSlotsByName(BMI)
    def RUN(self):
        burden=self.LB.text()
        length=self.LL.text()
        length=float(length)**2
        bmi=int(burden)//length
        if bmi < 18.5:
            self.SBM.setText("Your BMI ➜ %i"%bmi)
            self.SS.setText("Your BMI is Less :|")
        elif bmi in range(18,25):
            self.SBM.setText("Your BMI ➜ %i"%bmi)
            self.SS.setText("Your BMI is Good :)")
        elif bmi in range(25,30):
            self.SBM.setText("Your BMI ➜ %i"%bmi)
            self.SS.setText("Your BMI is Grate :|")
        elif bmi > 30:
            self.SBM.setText("Your BMI ➜ %i"%bmi)
            self.SS.setText("Your BMI is Very Grate :(")
    def CLOSEs(self):
        exit()
    def retranslateUi(self, BMI):
        _translate = QtCore.QCoreApplication.translate
        BMI.setWindowTitle(_translate("BMI", "MainWindow"))
        self.label_8.setText(_translate("BMI", "BMI"))
        self.Burden.setText(_translate("BMI", "Burden"))
        self.length.setText(_translate("BMI", "Length"))
        self.CLOSE.setText(_translate("BMI", "CLOSE"))
        self.label_7.setText(_translate("BMI", ":"))
        self.Bmi.setText(_translate("BMI", "BMI"))
        self.SBM.setText(_translate("BMI", "Unknow"))
        self.SS.setText(_translate("BMI", "Unknow"))
        self.Status.setText(_translate("BMI", "Status"))
        self.label_6.setText(_translate("BMI", ":"))
        self.Run.setText(_translate("BMI", "RUN"))
        self.gender.setItemText(0, _translate("BMI", "male"))
        self.gender.setItemText(1, _translate("BMI", "Fmale"))
        self.gender.setItemText(2, _translate("BMI", "Girl"))
        self.gender.setItemText(3, _translate("BMI", "Boy"))
        self.age.setText(_translate("BMI", "Age"))
import images.image_rc
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BMI = QtWidgets.QMainWindow()
    BMI.setStyleSheet("background-color:dark ;")
    ui = Ui_BMI()
    ui.setupUi(BMI)
    BMI.show()
    sys.exit(app.exec_())

